version: '3'
services:
  service-back:
    image: sauger92/tp2
    ports:
      - "8080:8080"
    environment: 
      - ENVIRONMENT=dev
  service-front:
    image: sauger92/tp2front
    ports: 
      - "8081:8081"
    environment: 
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1
