version: '3'
services:
  tp2-back:
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
    image: clairepas/tp2
  tp2-front:
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1
    image: clairepas/tp2-front

