version: '3'
services:
  launchBack:
    image: yrandill/my-python-app
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT='dev'
  launchFront:
    image: yrandill/tp2-front
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1