version: '3'
services:
  back_service:
    image: jeandslms/tp2_container:back_end
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=dev

  front_service:
    image: jeandslms/front_container:front
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=172.17.0.1
    links:
      - "back_service:back_end"
