version: '3'
services:
  back_service:
    image: jeandslms/tp2_container:back_end
    environment:
      - ENVIRONMENT=dev
#    volumes:
#      - data-volume:/var/lib/back_end

  front_service:
    image: jeandslms/front_container:front
    ports:
      - "8081:8081"
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=back_end
    links:
      - "back_service:back_end"
#    volumes:
#      - data-volume:/var/lib/front

#volumes:
#  data-volume:
