version: '3'
services:
  service-back:
    image: hrvly/back
#    ports:
#      - "8080:8080"
    environment:
      - ENVIRONMENT=dev
#    volumes:
#     - "logs"
  service-front:
    ports:
      - "8081:8081"
    image: hrvly/front
    environment:
      - APP_PORT=8081
      - WS_BACK_URL=back_end
    links:
      - "service-back:back_end"
#volumes:
#  logs:
