version: '3'
services:
        tp2back:
                image: ongphil/tp2back
                environment:
                        - ENVIRONMENT=dev
                ports:
                        - "8080:8080"
                          #volumes:
                          #- logs
        tp2front:
                image: ongphil/tp2front
                ports:
                        - "8081:8081"
                environment:
                        - APP_PORT=8081
                        - WS_BACK_URL=172.17.0.1
                          #volumes:
                          #logs:
